version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=StarterLoginDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./LogiBackend
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=StarterLoginDb;Username=postgres;Password=admin
      - JwtSettings__Secret=ThisIsAVerySecretKeyForJWTAuthentication2026!
      - JwtSettings__Issuer=StarterLoginApi
      - JwtSettings__Audience=StarterLoginFront
    ports:
      - "5170:80"
    depends_on:
      - database

  frontend:
    build:
      context: ./LogiFrontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
