services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=StarterLoginDb
    ports:
      - "5902:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d StarterLoginDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./LogiBackend
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=StarterLoginDb;Username=postgres;Password=admin
      - JwtSettings__Secret=ThisIsAVerySecretKeyForJWTAuthentication2026!
      - JwtSettings__Issuer=StarterLoginApi
      - JwtSettings__Audience=StarterLoginFront
    ports:
      - "5901:80"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./LogiFrontend
      dockerfile: Dockerfile
    ports:
      - "5900:80"
    depends_on:
      - backend

volumes:
  postgres_data:
